ci check implemented

diff --git a/.azure-pipelines/build-job.yml b/.azure-pipelines/build-job.yml
--- a/.azure-pipelines/build-job.yml
+++ b/.azure-pipelines/build-job.yml
@@ -114,6 +114,16 @@ jobs:
       env:
         ADO_ENABLE_LOGISSUE: true
 
+  # Verify if broken symlinks exist in the agent build
+  - bash: |
+      brokenSymlinks=$(find . -xtype l)
+      if [[ $brokenSymlinks != "" ]]; then
+          printf "Broken symlinks exist in the agent build:\n$brokenSymlinks\n"
+          exit 1
+      fi
+      echo "Broken symlinks not found in the agent build."
+    displayName: Check symlinks
+
   # Run l0 tests
   - ${{ if parameters.unitTests }}:
     - script: ${{ variables.devCommand }} testl0 Debug ${{ parameters.os }}-${{ parameters.arch }}
