canary branch parameter

diff --git a/.azure-pipelines/pipeline.yml b/.azure-pipelines/pipeline.yml
--- a/.azure-pipelines/pipeline.yml
+++ b/.azure-pipelines/pipeline.yml
@@ -89,10 +89,28 @@ stages:
           cd ./.azure-pipelines/scripts/
           npm install axios minimist
 
+          source="$(Build.SourceBranch)"
+          prefix="refs/heads/"
+
+          if [[ "${source}" == "${prefix}"* ]]; then
+              branch="${source#"${prefix}"}"
+
+              if [[ "${branch}" == "master" ]]; then
+                  branch="${{ parameters.branch }}"
+              fi
+
+              echo "Canary \"branch\" parameter: \"${branch}\""
+          else
+              echo "##vso[task.logissue type=error]This test is supported only if the build source branch name is specified directly"
+
+              exit 1
+          fi
+
           node ./run-and-verify.js \
               --projectUrl "$(CANARY_PROJECT_URL)" \
               --pipelineId "$(CANARY_PIPELINE_ID)" \
-              --token "$(CANARY_PAT)"
+              --token "$(CANARY_PAT)" \
+              --templateParameters "{ \"branch\": \"${branch}\" }"
         displayName: Test Proxy Agent
 
   # Windows (x64)
